name: Backend CI

on:
  workflow_dispatch:

  pull_request:
    branches:
      - main

jobs:
#  test:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4
#
#      - name: Set up Node.js
#        uses: actions/setup-python@v5
#        with:
#          node-version: latest
#
#      - name: Print a message for main branch
#        if: github.ref == 'refs/heads/main'
#        run: echo "This is the main branch."
#
#      - name: Print a message for non-main branches
#        if: github.ref != 'refs/heads/main'
#        run: echo "This is not the main branch."
#
#      - name: Install dependencies
#        run: |
#          python -m pip install --upgrade pip
#          pip install flake8 pytest
#        working-directory: ./backend
#
#      - name: Run tests with pytest
#        run: |
#          python test_app.py
#        working-directory: ./backend
#
#      - name: Debug message
#        if: env.DEBUG == 'true'
#        run: echo "Debugging is enabled."

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-python@v5
        with:
          node-version: latest

      - name: Print a message for main branch
        if: github.ref == 'refs/heads/main'
        run: echo "This is the main branch."

      - name: Print a message for non-main branches
        if: github.ref != 'refs/heads/main'
        run: echo "This is not the main branch."

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install flake8 pytest
            pip install flask-cors
        working-directory: ./backend

      - name: Run tests with pytest
        run: |
          python -m backend.test_app

      - name: Run Flake8
        run: |
          flake8 . --max-line-length=100
        working-directory: ./backend

      - name: Debug message
        if: env.DEBUG == 'true'
        run: echo "Debugging is enabled."

#  build:
#    needs: [test, lint]
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4
#
#      - name: Set up Node.js
#        uses: actions/setup-python@v5
#        with:
#          node-version: latest
#
#      - name: Install dependencies
#        run: |
#          python -m pip install --upgrade pip
#          pip install flake8 pytest
#        working-directory: ./backend
#
#      - name: Run tests with pytest
#        run: |
#          python test_app.py
#        working-directory: ./backend
#
#      - name: Debug message
#        if: env.DEBUG == 'true'
#        run: echo "Debugging is enabled."
#
#      - name: Publish test results
#        uses: actions/upload-artifact@v4.6.2
#        with:
#          name: test-results
#          path: build/
