name: Project workflow

on:
  workflow_dispatch:

  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Print a message for main branch
        if: github.ref == 'refs/heads/main'
        run: echo "This is the main branch."

      - name: Print a message for non-main branches
        if: github.ref != 'refs/heads/main'
        run: echo "This is not the main branch."

      - name: Install dependencies
        run: npm install
        working-directory: ./frontend

      - name: Run tests
        run: npm test
        working-directory: ./frontend

      - name: Debug message
        if: env.DEBUG == 'true'
        run: echo "Debugging is enabled."

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Print a message for main branch
        if: github.ref == 'refs/heads/main'
        run: echo "This is the main branch."

      - name: Print a message for non-main branches
        if: github.ref != 'refs/heads/main'
        run: echo "This is not the main branch."

      - name: Install dependencies
        run: npm install
        working-directory: ./frontend

      - name: Run ESLint
        run: npm run lint
        working-directory: ./frontend

      - name: Debug message
        if: env.DEBUG == 'true'
        run: echo "Debugging is enabled."

  build:
    needs: [test, lint]
    runs-on: ubuntu-latest
    steps:
      - name: Publish test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: test-results.xml